// Datos de la Biblioteca de recursos teóricos — Unidad didáctica 3 (Tecnologías Emergentes).
// Campos disponibles por recurso: ver README.md de la plantilla (TEUX_UD2-main).
// Los recursos 39 y 41 del documento de origen estaban duplicados/omitidos en su numeración
// (falta el nº 39 y el nº 41 aparece dos veces); aquí se han renumerado de forma correlativa.
const RESOURCES = [
  {
    id: 1,
    name: "The Uncontroversial \"Thingness\" of AI | Lucy Suchman",
    nameSpanish: "The Uncontroversial \"Thingness\" of AI | Lucy Suchman",
    section: "Explorar no es predecir",
    materialType: "Artículo académico",
    yearContext: "Publicado en 2023 en Big Data & Society, vol. 10, n.º 2.",
    language: "Inglés",
    relevance: "Este trabajo introduce una de las ideas centrales de la unidad, que es que la inteligencia artificial no constituye un objeto único y claramente definido, sino un conjunto de tecnologías, prácticas y discursos cuya ambigüedad contribuye a reforzar su capacidad de influencia. Suchman sostiene que describir las materializaciones concretas de aquello que se denomina inteligencia artificial constituye una intervención crítica y no una simple tarea descriptiva. Esta perspectiva fundamenta el enfoque de utilizar la especulación para analizar futuros posibles desde el presente y evitar planteamientos propios de la futurología.",
    embedUrl: "https://doi.org/10.1177/20539517231206794",
    link: "https://doi.org/10.1177/20539517231206794"
  },
  {
    id: 2,
    name: "How to Future | Scott Smith y Madeline Ashby",
    nameSpanish: "How to Future | Scott Smith y Madeline Ashby",
    section: "Explorar no es predecir",
    materialType: "Libro",
    yearContext: "Kogan Page publicó este libro en 2020.",
    language: "Inglés",
    relevance: "Este material ofrece un método práctico para trabajar con escenarios futuros sin recurrir a predicciones ni a ejercicios de imaginación desligados de la realidad. Su propuesta entiende el futuro como una herramienta para orientar decisiones presentes y proporciona un conjunto de técnicas que resultan especialmente útiles para estructurar ejercicios de prospectiva dentro del proceso de diseño.",
    link: "https://www.amazon.es/How-Future-Leading-Sense-making-Hyperchange/dp/1789664705"
  },
  {
    id: 3,
    name: "Speculative Everything | Anthony Dunne y Fiona Raby",
    nameSpanish: "Speculative Everything | Anthony Dunne y Fiona Raby",
    section: "Explorar no es predecir",
    materialType: "Libro",
    yearContext: "MIT Press publicó este libro en 2013.",
    language: "Inglés",
    relevance: "Este material es una referencia fundamental del diseño especulativo. Dunne y Raby defienden la especulación como una práctica orientada a generar reflexión y debate en lugar de estar orientada a producir soluciones definitivas. Desde esta perspectiva, el diseño permite explorar futuros alternativos y cuestionar los supuestos que condicionan el presente, en lugar de aceptar como inevitable un único escenario tecnológico.",
    link: "https://www.amazon.es/Speculative-Everything-Design-Fiction-Dreaming/dp/0262019841"
  },
  {
    id: 4,
    name: "The Manual of Design Fiction | Julian Bleecker, Nick Foster, Fabien Girardin y Nicolas Nova",
    nameSpanish: "The Manual of Design Fiction | Julian Bleecker, Nick Foster, Fabien Girardin y Nicolas Nova",
    section: "Explorar no es predecir",
    materialType: "Libro",
    yearContext: "Near Future Laboratory publicó este libro en 2022.",
    language: "Inglés",
    relevance: "Esta obra es un pilar especialmente relevante porque muestra cómo transformar la observación de una tecnología en una pregunta de diseño mediante la construcción de escenarios y ficciones de diseño.",
    embedUrl: "https://nearfuturelaboratory.com/library/2023/06/the-manual-of-design-fiction-softcover/",
    link: "https://nearfuturelaboratory.com/library/2023/06/the-manual-of-design-fiction-softcover/"
  },
  {
    id: 5,
    name: "Drivers and Signals | Institute for the Future (IFTF)",
    nameSpanish: "Drivers and Signals | Institute for the Future (IFTF)",
    section: "Explorar no es predecir",
    materialType: "Recursos metodológicos",
    yearContext: "Material publicado por el Institute for the Future (IFTF) de Palo Alto.",
    language: "Inglés",
    relevance: "Estos recursos amplían el trabajo sobre la identificación de señales débiles y tendencias que has realizado en la segunda unidad didáctica. En este material, las señales recopiladas durante el proceso de scanning se convierten en el punto de partida para la construcción de escenarios futuros. Es un recurso que proporciona un marco metodológico para relacionar fuerzas de cambio, señales emergentes y posibles evoluciones de un sistema.",
    embedUrl: "https://legacy.iftf.org/what-we-do/foresight-tools/signals/",
    link: "https://legacy.iftf.org/what-we-do/foresight-tools/signals/"
  },
  {
    id: 6,
    name: "The Social Control of Technology | David Collingridge",
    nameSpanish: "The Social Control of Technology | David Collingridge",
    section: "Explorar no es predecir",
    materialType: "Libro",
    yearContext: "Frances Pinter publicó este libro en 1980.",
    language: "Inglés",
    relevance: "Esta obra presenta el conocido dilema de Collingridge, uno de los fundamentos teóricos de la anticipación tecnológica. El autor explica que cuando una tecnología aún puede modificarse con facilidad resulta difícil prever todas sus consecuencias, pero que cuando sus efectos se hacen evidentes suele estar tan integrada en la sociedad que modificarla implica costes muy elevados. Este planteamiento justifica la necesidad de explorar escenarios futuros durante las primeras fases del desarrollo tecnológico.",
    link: "https://www.amazon.es/Social-Control-Technology-David-Collingridge/dp/0335100317"
  },
  {
    id: 7,
    name: "The Future Is Now: Diegetic Prototypes and the Role of Popular Films in Generating Real-World Technological Development | David A. Kirby",
    nameSpanish: "The Future Is Now: Diegetic Prototypes and the Role of Popular Films in Generating Real-World Technological Development | David A. Kirby",
    section: "Explorar no es predecir",
    materialType: "Artículo académico",
    yearContext: "Publicado en 2010 en Social Studies of Science, vol. 40, n.º 1.",
    language: "Inglés",
    relevance: "Este artículo introduce el concepto de \"prototipo diegético\", uno de los elementos centrales de esta unidad didáctica. Kirby analiza cómo determinadas tecnologías representadas en el cine, aunque todavía no existan, adquieren legitimidad y deseabilidad al integrarse de forma coherente en una narrativa. Esta aportación proporciona el fundamento teórico sobre el que posteriormente se desarrolla el enfoque metodológico del Design Fiction.",
    embedUrl: "https://doi.org/10.1177/0306312709338325",
    link: "https://doi.org/10.1177/0306312709338325"
  },
  {
    id: 8,
    name: "Design Fiction | Bruce Sterling",
    nameSpanish: "Design Fiction | Bruce Sterling",
    section: "Explorar no es predecir",
    materialType: "Ensayo publicado en una revista científica",
    yearContext: "Publicado en 2009 en ACM Interactions, vol. 16, n.º 3.",
    language: "Inglés",
    relevance: "Este ensayo constituye una de las primeras formulaciones del concepto de Design Fiction en la literatura académica. Sterling lo define como el uso deliberado de prototipos diegéticos para facilitar la comprensión de posibles cambios tecnológicos y favorecer la reflexión sobre ellos. Su lectura aporta el origen conceptual y terminológico del enfoque que se utiliza en esta unidad didáctica.",
    embedUrl: "https://doi.org/10.1145/1516016.1516021",
    link: "https://doi.org/10.1145/1516016.1516021"
  },
  {
    id: 9,
    name: "Hertzian Tales: Electronic Products, Aesthetic Experience, and Critical Design | Anthony Dunne",
    nameSpanish: "Hertzian Tales: Electronic Products, Aesthetic Experience, and Critical Design | Anthony Dunne",
    section: "Explorar no es predecir",
    materialType: "Libro",
    yearContext: "La edición revisada fue publicada en 2005 por MIT Press; la primera edición se publicó en 1999.",
    language: "Inglés",
    relevance: "Este es uno de los textos fundacionales del diseño crítico y antecede a Speculative Everything. Dunne desarrolla conceptos como la distinción entre diseño afirmativo y diseño crítico, que establecen las bases conceptuales del diseño especulativo.",
    link: "https://www.amazon.es/Hertzian-Tales-Electronic-Aesthetic-Experience/dp/0262042320"
  },
  {
    id: 10,
    name: "A Generic Foresight Process Framework | Joseph Voros",
    nameSpanish: "A Generic Foresight Process Framework | Joseph Voros",
    section: "El cono de futuros",
    materialType: "Artículo académico",
    yearContext: "Publicado en 2003 en Foresight, vol. 5, n.º 3, pp. 10-21.",
    language: "Inglés",
    relevance: "Este artículo presenta la formulación del cono de futuros que se utiliza en esta unidad didáctica como parte de un proceso más amplio de prospectiva estratégica. Voros organiza las categorías y explica el propósito de cada una.",
    embedUrl: "https://figshare.swinburne.edu.au/articles/journal_contribution/A_generic_foresight_process_framework/26244815",
    link: "https://figshare.swinburne.edu.au/articles/journal_contribution/A_generic_foresight_process_framework/26244815"
  },
  {
    id: 11,
    name: "The Futures Cone: Use and History | Joseph Voros",
    nameSpanish: "The Futures Cone: Use and History | Joseph Voros",
    section: "El cono de futuros",
    materialType: "Entrada de blog",
    yearContext: "Publicada originalmente en 2017 en The Voroscope, sujeta a revisiones posteriores.",
    language: "Inglés",
    relevance: "Esta publicación reconstruye la evolución del cono de futuros, identifica los trabajos que inspiraron su desarrollo y explica cómo ha evolucionado la herramienta a lo largo del tiempo. Su lectura permite entender el modelo como una construcción metodológica con una trayectoria definida y unos límites concretos, lo cual evita que sea interpretado como un esquema cerrado o universal.",
    embedUrl: "https://thevoroscope.com/2017/02/24/the-futures-cone-use-and-history/",
    link: "https://thevoroscope.com/2017/02/24/the-futures-cone-use-and-history/"
  },
  {
    id: 12,
    name: "The Futures of Everyday Life | Stuart Candy",
    nameSpanish: "The Futures of Everyday Life | Stuart Candy",
    section: "El cono de futuros",
    materialType: "Tesis doctoral",
    yearContext: "Presentada en 2010 en la University of Hawai‘i de Mānoa.",
    language: "Inglés",
    relevance: "Stuart Candy es uno de los principales impulsores del uso del cono de futuros en el ámbito del diseño y de los escenarios experienciales. Su investigación plantea que un escenario no constituye una predicción, sino una experiencia diseñada para explorar un futuro posible y favorecer la reflexión sobre las decisiones del presente. Esta perspectiva establece un puente entre el modelo conceptual del cono y los escenarios que desarrollarás a lo largo de esta unidad didáctica.",
    embedUrl: "https://doi.org/10.13140/RG.2.1.1840.0248",
    link: "https://doi.org/10.13140/RG.2.1.1840.0248"
  },
  {
    id: 13,
    name: "Possible Futures, Preferable Futures | Trevor Hancock y Clement Bezold",
    nameSpanish: "Possible Futures, Preferable Futures | Trevor Hancock y Clement Bezold",
    section: "El cono de futuros",
    materialType: "Artículo",
    yearContext: "Publicado en 1994 en Healthcare Forum Journal, vol. 37, n.º 2, pp. 23-29.",
    language: "Inglés",
    relevance: "Este artículo es uno de los antecedentes del modelo que desarrolló Joseph Voros. Los autores diferencian entre futuros posibles y futuros preferibles, una distinción que resulta fundamental para comprender que el futuro considerado más deseable no siempre coincide con el más probable. Esta tensión constituye uno de los ejes metodológicos de esta unidad didáctica.",
    embedUrl: "https://pubmed.ncbi.nlm.nih.gov/10132155/",
    link: "https://pubmed.ncbi.nlm.nih.gov/10132155/"
  },
  {
    id: 14,
    name: "The Futures Cone | Joseph Voros",
    nameSpanish: "The Futures Cone | Joseph Voros",
    section: "El cono de futuros",
    materialType: "Capítulo de un libro",
    yearContext: "Publicado en 2017 en el libro Handbook of Anticipation, del editor Roberto Poli, para la editorial Springer.",
    language: "Inglés",
    relevance: "Este capítulo ofrece la revisión más completa y actualizada del cono de futuros de Joseph Voros. Además de revisar la evolución histórica del modelo, Voros detalla el origen de cada una de sus categorías y precisa las aportaciones de los autores que contribuyeron a su desarrollo. Complementa el artículo anterior de Voros y amplía su contexto histórico y metodológico.",
    link: "https://www.amazon.es/Handbook-Anticipation-Theoretical-Applied-Decision/dp/331991555X"
  },
  {
    id: 15,
    name: "Scenario Planning at Shell | Pierre Wack",
    nameSpanish: "Scenario Planning at Shell | Pierre Wack",
    section: "El cono de futuros",
    materialType: "Artículo de referencia",
    yearContext: "Publicado en 1985 en Harvard Business Review, vol. 63, n.os 5 y 6.",
    language: "Inglés",
    relevance: "Este material constituye la referencia fundacional de la planificación por escenarios aplicada en Shell y representa uno de los antecedentes más influyentes de la prospectiva contemporánea. Wack sostiene que el valor de un escenario no reside en anticipar correctamente el futuro, sino en transformar los modelos mentales de quienes deben tomar decisiones. Esta idea fundamenta el enfoque de esta unidad didáctica, que entiende la construcción de escenarios como un ejercicio de exploración y aprendizaje más que como un intento de predicción.",
    embedUrl: "https://hbr.org/1985/09/scenarios-uncharted-waters-ahead",
    links: [
      { label: "Ver primer artículo", url: "https://hbr.org/1985/09/scenarios-uncharted-waters-ahead" },
      { label: "Ver segundo artículo", url: "https://hbr.org/1985/11/scenarios-shooting-the-rapids" }
    ]
  },
  {
    id: 16,
    name: "The Futures Wheel | Jerome C. Glenn",
    nameSpanish: "The Futures Wheel | Jerome C. Glenn",
    section: "Consecuencias de segundo y tercer orden",
    materialType: "Capítulo metodológico",
    yearContext: "Publicado en 2009 en Futures Research Methodology (versión 3.0), de The Millennium Project.",
    language: "Original en inglés; existe también una versión en español (La rueda del futuro), publicada en la versión 1.0 de Futures Research Methodology del Millennium Project.",
    relevance: "Este capítulo presenta la rueda del futuro, el método en el que se inspira la cascada de consecuencias que se desarrolla en esta unidad didáctica. A partir de un cambio inicial, la herramienta organiza de forma progresiva sus efectos de primer, segundo y tercer orden, lo que facilita una exploración sistemática de las consecuencias indirectas. La principal aportación de este material consiste en ayudar a superar el análisis centrado exclusivamente en los efectos inmediatos y ampliar la reflexión hacia impactos menos evidentes.",
    embedUrl: "https://www.millennium-project.org/publications/futures-research-methodology-version-3-0-2/",
    link: "https://www.millennium-project.org/publications/futures-research-methodology-version-3-0-2/"
  },
  {
    id: 17,
    name: "Why Things Bite Back | Edward Tenner",
    nameSpanish: "Why Things Bite Back | Edward Tenner",
    section: "Consecuencias de segundo y tercer orden",
    materialType: "Libro",
    yearContext: "Publicado en 1996 por Alfred A. Knopf.",
    language: "Inglés",
    relevance: "Edward Tenner analiza numerosos casos en los que una solución tecnológica termina generando problemas distintos o incluso agrava aquellos que pretendía resolver. Estos \"efectos de venganza\" muestran cómo las consecuencias no previstas pueden manifestarse con el paso del tiempo y modificar profundamente el funcionamiento de un sistema. Este es un material de referencia útil para entrenar la capacidad de anticipar efectos de segundo orden durante el proceso de diseño.",
    link: "https://www.amazon.es/Why-Things-Bite-Back-Consequences/dp/0679747567"
  },
  {
    id: 18,
    name: "The Unanticipated Consequences of Purposive Social Action | Robert K. Merton",
    nameSpanish: "The Unanticipated Consequences of Purposive Social Action | Robert K. Merton",
    section: "Consecuencias de segundo y tercer orden",
    materialType: "Artículo académico",
    yearContext: "Publicado en 1936 en American Sociological Review, vol. 1, n.º 6.",
    language: "Inglés",
    relevance: "En este artículo sobre las consecuencias no previstas de la acción social, Merton explica que hay factores que provocan que una acción intencional produzca efectos que nadie había anticipado. Esta perspectiva recuerda que el resultado que se busca representa sólo una parte de las transformaciones que una intervención puede desencadenar.",
    embedUrl: "https://doi.org/10.2307/2084615",
    link: "https://doi.org/10.2307/2084615"
  },
  {
    id: 19,
    name: "Thinking in Systems | Donella H. Meadows",
    nameSpanish: "Thinking in Systems | Donella H. Meadows",
    section: "Consecuencias de segundo y tercer orden",
    materialType: "Libro",
    yearContext: "Chelsea Green Publishing publicó este material en 2008. Existe una traducción al español (Pensar en sistemas).",
    language: "Inglés. Existe una traducción al español.",
    relevance: "Los conceptos de bucles reforzadores y compensadores permiten comprender por qué determinadas consecuencias indirectas tienden a amplificarse con el tiempo, mientras que otras se estabilizan o desaparecen. La lectura de este material aporta el marco sistémico necesario para interpretar la cascada de consecuencias como un proceso dinámico y no como una simple secuencia lineal de efectos.",
    link: "https://www.amazon.es/Pensar-sistemas-manual-iniciaci%C3%B3n-ENSAYO/dp/8412497783"
  },
  {
    id: 20,
    name: "Developing a Framework for Responsible Innovation | Jack Stilgoe, Richard Owen y Phil Macnaghten",
    nameSpanish: "Developing a Framework for Responsible Innovation | Jack Stilgoe, Richard Owen y Phil Macnaghten",
    section: "Consecuencias de segundo y tercer orden",
    materialType: "Artículo académico de acceso abierto",
    yearContext: "Publicado en 2013 en Research Policy, vol. 42, n.º 9, pp. 1568-1580.",
    language: "Inglés",
    relevance: "Los autores proponen un marco para la innovación responsable basado en los principios de anticipación, reflexividad, inclusión y capacidad de respuesta. Esta propuesta complementa la metodología de la cascada de consecuencias al incorporar una dimensión ética y normativa al proceso de diseño. Además de anticipar posibles impactos, plantea la responsabilidad de revisar las decisiones adoptadas y modificar el rumbo cuando sea necesario. Es un marco ampliamente utilizado en las políticas europeas de investigación e innovación, lo cual refuerza su relevancia para tu contexto profesional.",
    embedUrl: "https://doi.org/10.1016/j.respol.2013.05.008",
    link: "https://doi.org/10.1016/j.respol.2013.05.008"
  },
  {
    id: 21,
    name: "Do Politics Have Artifacts? | Bernward Joerges",
    nameSpanish: "Do Politics Have Artifacts? | Bernward Joerges",
    section: "La política de los artefactos",
    materialType: "Artículo académico",
    yearContext: "Publicado en 1999 en Social Studies of Science, vol. 29, n.º 3.",
    language: "Inglés",
    relevance: "Este artículo es una respuesta crítica a la tesis de Langdon Winner sobre la dimensión política de los artefactos. Joerges revisa el conocido caso de los puentes diseñados por Robert Moses y argumenta que la evidencia disponible no permite sostener algunas de las afirmaciones con la contundencia con la que suelen presentarse. Es un recurso que permite analizar el debate desde distintas perspectivas, fomenta una actitud crítica ante los casos ampliamente difundidos y refuerza la importancia de evaluar las evidencias que sustentan cada argumento.",
    embedUrl: "https://doi.org/10.1177/030631299029003004",
    link: "https://doi.org/10.1177/030631299029003004"
  },
  {
    id: 22,
    name: "Where Are the Missing Masses? | Bruno Latour",
    nameSpanish: "Where Are the Missing Masses? | Bruno Latour",
    section: "La política de los artefactos",
    materialType: "Capítulo de un libro",
    yearContext: "MIT Press publicó este material en 1992 en Shaping Technology / Building Society, de los editores Wiebe Bijker y John Law.",
    language: "Inglés",
    relevance: "Este material presenta el ejemplo del cierrapuertas para introducir la capacidad de los objetos técnicos de influir en el comportamiento humano. Latour muestra cómo una tarea inicialmente desempeñada por las personas puede delegarse en un artefacto que pasa a regular determinadas acciones de manera automática. Se trata de una de las introducciones más accesibles a la teoría del actor-red y constituye una referencia fundamental para comprender cómo los objetos participan en la configuración de las prácticas sociales.",
    embedUrl: "https://www.sfu.ca/~andrewf/Latour_MissingMasses.pdf",
    link: "https://www.sfu.ca/~andrewf/Latour_MissingMasses.pdf"
  },
  {
    id: 23,
    name: "Reassembling the Social | Bruno Latour",
    nameSpanish: "Reassembling the Social | Bruno Latour",
    section: "La política de los artefactos",
    materialType: "Libro",
    yearContext: "Oxford University Press publicó este libro en 2005. Existe una traducción al español (Reensamblar lo social, de la editorial Manantial).",
    language: "Original en inglés; traducción al español disponible.",
    relevance: "Esta obra desarrolla de forma sistemática la teoría del actor-red y propone entender los fenómenos sociales como el resultado de las relaciones entre actores humanos y no humanos. Aporta un marco para comprender que las consecuencias de una tecnología no pueden atribuirse únicamente al objeto, sino al conjunto de relaciones que lo hacen posible. La introducción resulta especialmente útil para entender por qué el mapeo de actores constituye una herramienta clave para analizar los efectos de un sistema.",
    link: "https://www.amazon.es/Reensamblar-Lo-Social-Bruno-Latour/dp/9875001147"
  },
  {
    id: 24,
    name: "The De-Scription of Technical Objects | Madeleine Akrich",
    nameSpanish: "The De-Scription of Technical Objects | Madeleine Akrich",
    section: "La política de los artefactos",
    materialType: "Capítulo de un libro",
    yearContext: "Publicado en 1992 en Shaping Technology / Building Society.",
    language: "Inglés",
    relevance: "Madeleine Akrich plantea que todo objeto técnico incorpora un \"guion\" que anticipa quién lo utilizará, de qué manera y bajo qué supuestos. Esta idea permite analizar cómo el diseño condiciona determinados comportamientos y excluye otros que son posibles. Es una herramienta especialmente útil para identificar las expectativas que un sistema proyecta sobre sus personas usuarias y reconocer a quién incluye o deja al margen desde su propia configuración.",
    embedUrl: "https://mitpress.mit.edu/9780262521949/shaping-technology-building-society/",
    link: "https://mitpress.mit.edu/9780262521949/shaping-technology-building-society/"
  },
  {
    id: 25,
    name: "Moralizing Technology | Peter-Paul Verbeek",
    nameSpanish: "Moralizing Technology | Peter-Paul Verbeek",
    section: "La política de los artefactos",
    materialType: "Libro",
    yearContext: "University of Chicago Press publicó este material en 2011.",
    language: "Inglés",
    relevance: "Verbeek sostiene que las tecnologías no sólo cumplen una función instrumental, sino que también median en las decisiones y los valores de las personas. Desde esta perspectiva, los objetos técnicos participan en la construcción de criterios morales y orientan determinadas formas de actuar. Este libro amplía la reflexión sobre la dimensión política de los artefactos y subraya que toda decisión de diseño incorpora, de forma explícita o implícita, una dimensión ética.",
    link: "https://www.amazon.es/Moralizing-Technology-Understanding-Designing-Morality/dp/0226852938"
  },
  {
    id: 26,
    name: "Dreamscapes of Modernity: Sociotechnical Imaginaries and the Fabrication of Power | Sheila Jasanoff y Sang-Hyun Kim (eds.)",
    nameSpanish: "Dreamscapes of Modernity: Sociotechnical Imaginaries and the Fabrication of Power | Sheila Jasanoff y Sang-Hyun Kim (eds.)",
    section: "La política de los artefactos",
    materialType: "Volumen académico editado",
    yearContext: "University of Chicago Press publicó este material en 2015.",
    language: "Inglés",
    relevance: "Esta obra introduce el concepto de imaginarios sociotécnicos para explicar cómo las visiones compartidas del futuro influyen en el desarrollo de las tecnologías, las políticas públicas y las instituciones. Su aportación amplía el análisis de la dimensión política de los artefactos al incorporar factores culturales, sociales e institucionales que trascienden el propio objeto técnico. Constituye una referencia especialmente valiosa para comprender cómo las decisiones de diseño se inscriben en contextos culturales diversos y participan en la construcción de futuros colectivos.",
    link: "https://www.amazon.es/Dreamscapes-Modernity-Sociotechnical-Imaginaries-Fabrication-ebook/dp/B013JTNNBQ"
  },
  {
    id: 27,
    name: "Moffatt vs. Air Canada",
    nameSpanish: "Moffatt vs. Air Canada",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Resolución judicial",
    yearContext: "El Tribunal de Resoluciones Civiles de Columbia Británica (Canadá) dictó esta resolución (2024 BCCRT 149) el 14 de febrero de 2024.",
    language: "Inglés",
    relevance: "En esta resolución, un tribunal determinó que Air Canada era responsable de la información incorrecta proporcionada por su asistente conversacional y rechazó el argumento de que el sistema funcionara como una entidad independiente de la empresa. El caso permite comprender cómo se atribuye la responsabilidad jurídica cuando intervienen sistemas de inteligencia artificial y ofrece un ejemplo de cómo una consecuencia que se podría haber anticipado puede convertirse en un precedente legal.",
    embedUrl: "https://canlii.ca/t/k2spq",
    link: "https://canlii.ca/t/k2spq"
  },
  {
    id: 28,
    name: "Crisis de los términos de servicio de Adobe",
    nameSpanish: "Crisis de los términos de servicio de Adobe",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Cobertura de prensa especializada y comunicados institucionales",
    yearContext: "Junio de 2024.",
    language: "Inglés",
    relevance: "Este caso documenta la controversia que se generó tras la actualización de las condiciones de uso de Adobe, que incluyó una cláusula relativa al acceso a los contenidos de las personas usuarias para determinadas tareas de revisión. Una parte importante de la comunidad creativa interpretó esa modificación como una autorización para utilizar esos contenidos en el entrenamiento de modelos de inteligencia artificial. La reacción pública llevó a la empresa a publicar varias aclaraciones y a comprometerse a redactar unos términos de servicio más claros. El caso permite analizar cómo una modificación aparentemente menor puede desencadenar una cascada de consecuencias sociales, reputacionales y políticas.",
    embedUrl: "https://blog.adobe.com/en/publish/2024/06/10/updating-adobes-terms-of-use",
    links: [
      { label: "Ver comunicado oficial", url: "https://blog.adobe.com/en/publish/2024/06/10/updating-adobes-terms-of-use" },
      { label: "Ver cobertura del caso", url: "https://petapixel.com/2024/06/07/adobe-responds-to-terms-of-use-controversy-says-it-isnt-spying-on-users/" }
    ]
  },
  {
    id: 29,
    name: "AI Incident Database | Responsible AI Collaborative",
    nameSpanish: "AI Incident Database | Responsible AI Collaborative",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Base de datos en línea de acceso abierto",
    yearContext: "Recurso mantenido y actualizado de forma continua.",
    language: "Inglés",
    relevance: "Este repositorio contiene incidentes reales relacionados con sistemas de inteligencia artificial y los clasifica según su naturaleza y contexto. Constituye una herramienta especialmente útil para identificar riesgos que ya fueron documentados en tecnologías similares a las que estás analizando y facilita el desarrollo de escenarios fundamentados en casos reales. Consultar este recurso te permite transformar hipótesis abstractas en situaciones contrastadas y aporta evidencias para enriquecer el análisis prospectivo.",
    embedUrl: "https://incidentdatabase.ai/",
    link: "https://incidentdatabase.ai/"
  },
  {
    id: 30,
    name: "Mobley vs. Workday",
    nameSpanish: "Mobley vs. Workday",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Litigio en curso",
    yearContext: "Este procedimiento se inició en 2023 ante el Tribunal Federal del Distrito Norte de California.",
    language: "Inglés",
    relevance: "Este procedimiento judicial constituye un ejemplo especialmente significativo para analizar los sistemas automatizados de selección de personal. El demandante sostiene que fue descartado por motivos de edad en numerosos procesos de contratación como consecuencia del funcionamiento del sistema. El caso resulta relevante porque plantea la posible responsabilidad del proveedor tecnológico, además de la de las organizaciones que utilizan la herramienta. Se trata de un ejemplo de cómo una consecuencia inicialmente hipotética puede convertirse en un procedimiento judicial con implicaciones regulatorias.",
    embedUrl: "https://www.courtlistener.com/docket/66831340/mobley-v-workday-inc/",
    link: "https://www.courtlistener.com/docket/66831340/mobley-v-workday-inc/"
  },
  {
    id: 31,
    name: "Base de datos de alucinaciones de IA en tribunales | Damien Charlotin (HEC Paris)",
    nameSpanish: "Base de datos de alucinaciones de IA en tribunales | Damien Charlotin (HEC Paris)",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Base de datos en línea de acceso abierto",
    yearContext: "Material actualizado de forma continua.",
    language: "Inglés",
    relevance: "Este repositorio reúne casos judiciales en los que profesionales del ámbito jurídico presentaron ante los tribunales información generada por sistemas de inteligencia artificial que resultó ser falsa. Permite estudiar una cadena completa de consecuencias en la que el sistema genera información aparentemente verosímil, la persona usuaria confía en ella y el error termina produciendo efectos jurídicos y profesionales. Constituye una fuente especialmente útil para comprender cómo la delegación de tareas en sistemas automatizados puede desencadenar consecuencias de gran alcance.",
    embedUrl: "https://www.damiencharlotin.com/hallucinations/",
    link: "https://www.damiencharlotin.com/hallucinations/"
  },
  {
    id: 32,
    name: "The New York Times vs. OpenAI y Microsoft",
    nameSpanish: "The New York Times vs. OpenAI y Microsoft",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Litigio en curso sobre propiedad intelectual",
    yearContext: "Este procedimiento se inició en 2023 ante el Tribunal del Distrito Sur de Nueva York.",
    language: "Inglés",
    relevance: "Más allá del debate sobre los derechos de propiedad intelectual asociados al entrenamiento de modelos de inteligencia artificial, este procedimiento ha generado una consecuencia regulatoria de especial interés cuando la obligación judicial de conservar determinados registros de conversaciones de personas usuarias entró en tensión con los principios europeos de minimización y protección de datos. El caso constituye un ejemplo de cómo una controversia jurídica puede producir efectos que trascienden el conflicto inicial y afectar a distintos marcos regulatorios.",
    links: [
      { label: "Ver expediente judicial", url: "https://www.courtlistener.com/docket/68117049/the-new-york-times-company-v-microsoft-corporation/" },
      { label: "Ver demanda original (PDF)", url: "https://nytco-assets.nytimes.com/2023/12/NYT_Complaint_Dec2023.pdf" }
    ]
  },
  {
    id: 33,
    name: "El mapa de calor global de Strava",
    nameSpanish: "El mapa de calor global de Strava",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Caso documentado en prensa internacional",
    yearContext: "2018.",
    language: "Inglés",
    relevance: "Este caso constituye un ejemplo paradigmático de consecuencia de segundo orden. La publicación de un mapa de calor elaborado a partir de datos agregados de actividad física parecía una funcionalidad inocua, pero en determinadas zonas remotas permitió identificar bases militares y rutas de patrulla debido a que los únicos usuarios activos eran militares. El caso demuestra cómo la combinación de datos aparentemente anónimos puede revelar información sensible y pone de manifiesto la importancia de analizar los efectos indirectos derivados de las decisiones de diseño.",
    embedUrl: "https://www.theguardian.com/world/2018/jan/28/fitness-tracking-app-gives-away-location-of-secret-us-army-bases",
    link: "https://www.theguardian.com/world/2018/jan/28/fitness-tracking-app-gives-away-location-of-secret-us-army-bases"
  },
  {
    id: 34,
    name: "DeepSeek y la caída de un supuesto de coste",
    nameSpanish: "DeepSeek y la caída de un supuesto de coste",
    section: "Cuando la consecuencia ya ocurrió",
    materialType: "Caso de industria documentado mediante cobertura técnica y periodística",
    yearContext: "2025.",
    language: "Inglés",
    relevance: "La aparición de un modelo de lenguaje desarrollado con un coste muy inferior al que se consideraba necesario cuestionó el supuesto de que únicamente unas pocas organizaciones podían afrontar la inversión requerida. Este episodio resulta especialmente útil para el trabajo con escenarios, ya que recuerda que incluso las hipótesis consideradas más sólidas pueden cambiar de forma repentina. Constituye un ejemplo de cómo un escenario inicialmente plausible puede materializarse antes de lo esperado y alterar las condiciones sobre las que se había construido el análisis.",
    embedUrl: "https://newsletter.semianalysis.com/p/deepseek-debates",
    link: "https://newsletter.semianalysis.com/p/deepseek-debates"
  },
  {
    id: 35,
    name: "The Computer for the 21st Century | Mark Weiser",
    nameSpanish: "The Computer for the 21st Century | Mark Weiser",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Artículo seminal",
    yearContext: "Publicado en 1991.",
    language: "Inglés",
    relevance: "Este texto fundacional sobre la computación ubicua es el punto de partida para comprender cómo la informática abandona progresivamente el ordenador como único lugar de interacción. Weiser plantea que las tecnologías más exitosas son aquellas que terminan por desaparecer del foco de atención y se integran de forma natural en el entorno cotidiano. Es una lectura que proporciona el marco conceptual para entender los objetos inteligentes y la interacción ambiental como una evolución de la informática tradicional.",
    embedUrl: "https://doi.org/10.1038/scientificamerican0991-94",
    link: "https://doi.org/10.1038/scientificamerican0991-94"
  },
  {
    id: 36,
    name: "Radical Technologies | Adam Greenfield",
    nameSpanish: "Radical Technologies | Adam Greenfield",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Libro",
    yearContext: "Este libro fue publicado en 2017.",
    language: "Original en inglés; existe una edición en español publicada por la editorial Caja Negra.",
    relevance: "Este libro analiza cómo tecnologías como el internet de las cosas, la automatización, la inteligencia artificial o las plataformas digitales pasan a formar parte del paisaje cotidiano hasta hacerse prácticamente invisibles. Greenfield examina sus implicaciones sociales, políticas y materiales, con especial atención a cuestiones como la privacidad, la seguridad o la dependencia tecnológica. Complementa la visión fundacional de Weiser con una lectura crítica sobre las consecuencias de esa integración.",
    link: "https://www.amazon.es/Radical-Technologies-Adam-Greenfield/dp/178478043X"
  },
  {
    id: 37,
    name: "Calm Technology | Amber Case",
    nameSpanish: "Calm Technology | Amber Case",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Libro",
    yearContext: "Este material se publicó en 2015.",
    language: "Inglés",
    relevance: "Case desarrolla el concepto de tecnología calma y lo traduce en principios concretos de diseño. Su propuesta consiste en crear sistemas capaces de informar y asistir sin reclamar constantemente la atención de las personas usuarias. Este libro constituye una guía práctica sobre cómo diseñar interacciones respetuosas con la atención humana y ofrece un contrapunto directo a los modelos basados en la captura permanente de atención.",
    embedUrl: "https://calmtech.com/book",
    link: "https://calmtech.com/book"
  },
  {
    id: 38,
    name: "Implicit Human-Computer Interaction Through Context | Albrecht Schmidt",
    nameSpanish: "Implicit Human-Computer Interaction Through Context | Albrecht Schmidt",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Artículo académico",
    yearContext: "Este material se publicó en el año 2000.",
    language: "Inglés",
    relevance: "Este es uno de los primeros trabajos que sistematiza la interacción implícita (aquella que el sistema deduce a partir del contexto sin necesidad de recibir instrucciones explícitas). Resulta especialmente relevante porque explica cómo el diseño desplaza parte del control desde la persona usuaria hacia el sistema y cuáles son las implicaciones de esa transferencia para la experiencia de uso.",
    embedUrl: "https://doi.org/10.1007/BF01324126",
    link: "https://doi.org/10.1007/BF01324126"
  },
  {
    id: 39,
    name: "A Taxonomy of Mixed Reality Visual Displays | Paul Milgram y Fumio Kishino",
    nameSpanish: "A Taxonomy of Mixed Reality Visual Displays | Paul Milgram y Fumio Kishino",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Artículo académico",
    yearContext: "Este artículo se publicó en 1994.",
    language: "Inglés",
    relevance: "Este artículo es la referencia clásica que define el continuo entre realidad física y realidad virtual e introduce las categorías de realidad aumentada y realidad mixta. Los contenidos de esta unidad didáctica utilizan este marco para situar las distintas tecnologías de realidad extendida y comprender que no constituyen categorías aisladas, sino posiciones dentro de un mismo continuo de interacción.",
    embedUrl: "https://globals.ieice.org/en_transactions/information/10.1587/e77-d_12_1321/_p",
    link: "https://globals.ieice.org/en_transactions/information/10.1587/e77-d_12_1321/_p"
  },
  {
    id: 40,
    name: "The Design of Implicit Interactions | Wendy Ju y Larry Leifer",
    nameSpanish: "The Design of Implicit Interactions | Wendy Ju y Larry Leifer",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Artículo académico",
    yearContext: "Este material se publicó en 2008 en Design Issues, 24(3), 72-84.",
    language: "Inglés",
    relevance: "Este texto traslada el concepto de interacción implícita desde la investigación tecnológica al ámbito del diseño de experiencia de usuario. Los autores proponen principios para que los sistemas actúen a partir del contexto sin resultar invasivos ni generar sensación de pérdida de control. Complementa el trabajo de Schmidt y aporta herramientas proyectuales directamente aplicables al diseño de productos digitales.",
    embedUrl: "https://doi.org/10.1162/desi.2008.24.3.72",
    link: "https://doi.org/10.1162/desi.2008.24.3.72"
  },
  {
    id: 41,
    name: "The Coming Age of Calm Technology | Mark Weiser y John Seely Brown",
    nameSpanish: "The Coming Age of Calm Technology | Mark Weiser y John Seely Brown",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Capítulo de un libro",
    yearContext: "Este capítulo se publicó en 1997 en Beyond Calculation: The Next Fifty Years of Computing.",
    language: "Inglés",
    relevance: "En este texto se formula el concepto original de tecnología calma. Los autores defienden que la tecnología debe desplazarse entre el centro y la periferia de la atención según las necesidades de cada momento, sin competir continuamente por captar el foco de las personas usuarias. Esta idea constituye el fundamento teórico del libro de Amber Case y ofrece el soporte conceptual de los patrones de interacción ambiental que esta unidad didáctica propone analizar.",
    embedUrl: "https://link.springer.com/book/10.1007/978-1-4612-0685-9",
    link: "https://link.springer.com/book/10.1007/978-1-4612-0685-9"
  },
  {
    id: 42,
    name: "What Is Mixed Reality? | Maximilian Speicher, Brian D. Hall y Michael Nebeling",
    nameSpanish: "What Is Mixed Reality? | Maximilian Speicher, Brian D. Hall y Michael Nebeling",
    section: "Objetos inteligentes, realidad extendida e interacción",
    materialType: "Artículo de congreso",
    yearContext: "Este artículo se publicó en 2019 en Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems (pp. 1-15).",
    language: "Inglés",
    relevance: "Este artículo revisa críticamente las definiciones de realidad mixta y realidad extendida que han surgido desde la propuesta de Milgram y Kishino. Los autores muestran cómo la evolución tecnológica ha difuminado las fronteras entre estas categorías y proponen un marco actualizado para describir experiencias inmersivas. Ofrece una terminología más precisa y adaptada a los desarrollos contemporáneos en interacción y diseño de experiencias inmersivas.",
    embedUrl: "https://doi.org/10.1145/3290605.3300767",
    link: "https://doi.org/10.1145/3290605.3300767"
  }
];
